### PR TITLE
add compile time select with bitmask

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Independent of other more elaborate `shuffle` and `permute` things, this could be a nice addition (and it was @HadrienG2 's initial request)

**Comment by franPul** [comment]
Hi, is there any reason why this is not being merged?

**Comment by JohanMabille** [comment]
Because it's not finished (the test of the new feature is not passing, other tests are removed from the cmake, etc...)

**Comment by serge-sans-paille** [comment]
Obsoleted by a5ac6b5cff6eba25ed23bf5ecb310c9e2aed4d3c

**Pull request closed without merging**
