### PR TITLE
Improve xsimd::abs coverage

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Let's open a discussion here: the test commented out in this PR don't pass, and I fail to understand why. Any hint?

**Comment by wolfv** [comment]
can you remove the commenting out and let's see what CI says?

**Comment by serge-sans-paille** [comment]
@wolfv here is CI output :-) Have fun

**Comment by serge-sans-paille** [comment]
no longer relevant, @JohanMabille did a great job there.

**Pull request closed without merging**
