### PR TITLE
Fix sincos implementation to cope with Emscripten

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@JohanMabille / @anutosh491  just disabling the #ifdef seems to work, can you explain that?

**Comment by JohanMabille** [comment]
Looks like the versions of Firefox and the SDKs that we use for testing have changed since we introduced this workaround, maybe the intrinsics have been fixed? Or maybe we are not testing what we think,meaning we don't build with WASM intrinsics, but rather with SSE2 that are then used to generate WASM? This latter seems highly improbable to me, but that's a possbility.

**Comment by serge-sans-paille** [comment]
Anyway I double checked the sincos implementation compared to calling sin and cos, and it's *exactly* the same.

**Comment by JohanMabille** [comment]
x-files-paranormal

**Comment by JohanMabille** [comment]
(I have the feeling that I'm posting this GIF way too often, not a good sign)

**Comment by serge-sans-paille** [comment]
@JohanMabille I think it's ok to merge this patch, but I ultimately leave it to you.

**Pull request merged**
