### PR TITLE
Test and fill holes in xsimd scalar api

### LINKED ISSUE #784: separate scalar mode tests from full vector tests
As discussed at https://github.com/xtensor-stack/xsimd/issues/756 and at https://github.com/serge-sans-paille/pythran/issues/1999 ,  xsimd is designed to work in scalar mode on all architectures, even those without SIMD vector acceleration. pythran requires xsimd even on "unsupported" arches in order to access scalar mode.

Currently xsimd tests address full functionality and therefore fail on "unsupported" (SIMD-free) architectures.

The tests are defined in XSIMD_TESTS in test/CMakeLists.txt.  It would be useful if that list of tests could be split into scalar-mode and vector-mode tests (e.g. create two lists, XSIMD_SCALAR_TESTS and XSIMD_VECTOR_TESTS), with some kind of new cmake option to switch off XSIMD_VECTOR_TESTS when running on SIMD-free architectures.

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Fix #784

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
The goal here is

1. make sure every vector function has it scalar counter part available
2. make sure the scalar API is compilable on every target, even those where we don't have batch support

**Comment by serge-sans-paille** [comment]
cc @JohanMabille : while doing this I already found an implementation bug in the vector version of `bitwise_andnot` and a compiler (MSVC) bug on avx512f... that goes way behond just the scalar part. i'll `rebase -i` once I'm finished

**Comment by serge-sans-paille** [comment]
@JohanMabille : ready for review!

**Comment by JohanMabille** [comment]
Good catch for the bitwise_andnot bug and the compiler bug!

**Pull request merged**
