### PR TITLE
Release 13.1.0

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@JohanMabille looks good on my side, can you confirm?

**Comment by JohanMabille** [comment]
Yes, although I find it annoying to have this CI failure for a while. It looks like doctest is not available anymore on some platform, and is not activaly maintained anymore. We should probably migrate to gatch 2.

**Review by JohanMabille — APPROVED** [review]

**Comment by serge-sans-paille** [comment]
agreed! thanks

**Comment by serge-sans-paille** [comment]
(tagging done)

**Pull request merged**
