### PR TITLE
Generic, simple implementation fox xsimd::compress

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Related to #975

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@avitase : current generic implementation probably under-performs, I'll check that :-)

**Comment by serge-sans-paille** [comment]
faster generic version! I'll add an AVX512 version at the end of the day.

**Comment by serge-sans-paille** [comment]
@luhenry : out of curiosity, is there a specific riscv instruction that could help here? I'm fine with keeping the generic implementation for riscv (just like for arm and wasm) but I'm just curious.

**Comment by luhenry** [comment]
@serge-sans-paille probably the vcompress.vm instruction. See https://github.com/riscv/riscv-v-spec/blob/fc76ec73fc1dd4531360ee8f3138f79f02e8b1b0/v-spec.adoc#165-vector-compress-instruction for details

**Pull request merged**
