### PR TITLE
Implement xsimd::swizzle

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
missing int8 / int16 implementation on Intel, and arm implementation (cc @JohanMabille for the ARM part, are you interested in implementing it?)

**Comment by amyspark** [comment]
This implementation seems to hardcode the batch size depending on the instruction set architecture, am I correct?

**Comment by serge-sans-paille** [comment]
> This implementation seems to hardcode the batch size depending on the instruction set architecture, am I correct?

That's the case of all operations for xsimd8.x, or maybe I misunderstood your question?

**Comment by amyspark** [comment]
> > This implementation seems to hardcode the batch size depending on the instruction set architecture, am I correct?
> 
> That's the case of all operations for xsimd8.x, or maybe I misunderstood your question?

I'd expected the operation to take two batch<T, A> parameters, but I guess the use of batch_constant makes the size dependency explicit.

**Comment by JohanMabille** [comment]
> missing int8 / int16 implementation on Intel, and arm implementation (cc @JohanMabille for the ARM part, are you interested in implementing it?)

Yep will do.

**Comment by serge-sans-paille** [comment]
@JohanMabille I've squashed my PR, you can rebase on it to start testing.

**Comment by amyspark** [comment]
hey, any news as to this MR and #653?

**Comment by JohanMabille** [comment]
I have been swamped with other tasks for a few days, I wll try to get back to this in the end of the week. Swizzle is implemented for NEON64, the remaining issue is for NEON where no table instruction is available.

**Comment by serge-sans-paille** [comment]
non trivial rebase here. @JohanMabille I've rebase that one on master and filtered out the arm tests so that it can land

**Comment by JohanMabille** [comment]
Ok let's merge it when it's green, I'll try to get back to the ARM implementation after.

**Pull request merged**
