### PR TITLE
Added aarch64 tests back

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by wolfv** [comment]
@JohanMabille I am currently paying for a Graviton 2 instance on AWS (10$ a month). We can easily install a self-hosted runner on it to run the tests if we want to.

**Comment by JohanMabille** [comment]
Yeah looks like we don't really have the choice :s I've struggled a lot with this when I mgrated the CI from travis to Azure, and honestly I still don't understand why it fails.

**Comment by pitrou** [comment]
@cyb70289 FYI :-)

**Comment by serge-sans-paille** [comment]
Obsoleted by #479

**Pull request closed without merging**
