### PR TITLE
FixAVX 512 build under VS2015

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Related to #421

### CODE REVIEW

**Comment by JohanMabille** [comment]
:tada:

**Comment by serge-sans-paille** [comment]
@JohanMabille green again! I feel like the green vador of AVX512

**Comment by SylvainCorlay** [comment]
Should we go ahead and merge this?

**Comment by JohanMabille** [comment]
Not yet.

**Comment by JohanMabille** [comment]
> I feel like the green vador of AVX512

**Comment by serge-sans-paille** [comment]
cc @JohanMabille https://github.com/xtensor-stack/xsimd/pull/451/commits/28e1b625837274c3911bb038fee7118728c4a8a2 passes validation, which validates the AVX512 implementation fallbacks, according to me.
Once you confirm, I'll revert that one last commit and we should be ready to merge.

**Comment by JohanMabille** [comment]
I confirm!

**Comment by JohanMabille** [comment]
Awesome!

**Comment by pitrou** [comment]
This seems to have fixed our build issues. Thank you!

**Pull request merged**
