### PR TITLE
Simplify expand implementation

### PR DESCRIPTION
**Pull request by avitase**
The previous implementation relied on a raw for-loop that compiles an index sequence that was subsequently fed into a combination of select and swizzle. The new version doesn't need the latter two steps but compiles the result directly in the for-loop.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
On my setup, your code 4 times slower than mine, can you confirm on your side?

**Comment by avitase** [comment]
Oo. What exactly did you run to test it?

**Comment by serge-sans-paille** [comment]
there was a problem in my test. Let me redo the benchmark (!)

**Comment by serge-sans-paille** [comment]
My version is now only three time faster. The benchmark:

```c++
$ cat a.cpp b.cpp
#include <xsimd/xsimd.hpp>

__attribute__((noinline)) xsimd::batch<uint32_t, xsimd::sse4_2> doit(xsimd::batch<uint32_t, xsimd::sse4_2> const& in, xsimd::batch_bool<uint32_t, xsimd::sse4_2> const& mask);

int main(int argc, char** argv)
{
  int n = atoi(argv[1]);
  auto in = xsimd::batch<uint32_t, xsimd::sse4_2>::load_unaligned((uint32_t*)argv[0]);
  auto mask = xsimd::batch_bool<uint32_t, xsimd::sse4_2>{true, false, false, true};
  for(int i = 0; i <n ; ++i)
    auto volatile drop = doit(in, mask);
  return 0;
}

#include <xsimd/xsimd.hpp>

__attribute__((noinline)) auto doit(xsimd::batch<uint32_t, xsimd::sse4_2> const& in, xsimd::batch_bool<uint32_t, xsimd::sse4_2> const& mask) {
  return xsimd::expand(in, mask);
}

$ clang++ -I../include -O2 -msse4.2 a.cpp -DNDEBUG -O3 b.cpp
$ time ./a.out 400000000
```

**Comment by avitase** [comment]
That's weird. Here are my results with g++-11.4.0 for your version:

```
build$ git log | head -n1 && g++ -I../include -O2 -march=native a.cpp -DNDEBUG -O3 b.cpp && time ./a.out 400000000
commit bbe135454c0043afdfe4115744b8b5c6ff1641e1

real	0m3.009s
user	0m3.009s
sys	0m0.000s
```

and here for my version:

```
build$ git log | head -n1 && g++ -I../include -O2 -march=native a.cpp -DNDEBUG -O3 b.cpp && time ./a.out 400000000
commit 0f6c5837abe9d55aed39fe6ff22d7a257a273ccb

real	0m2.300s
user	0m2.300s
sys	0m0.000s
```

**Comment by serge-sans-paille** [comment]
Got it! clang seems to optimize the code differently from gcc. I'll try to express the intent differently so that they both generate the same (fast) code

**Comment by serge-sans-paille** [comment]
@avitase I just oushed a version that make gcc and clang generate close code, can you give it a shot (with both compilers !) And then maybe combine your approach with mine and see how it goes? Thanks!

**Comment by avitase** [comment]
Your solution is now consistently faster for both GCC and Clang! Great work, thanks!

**Pull request closed without merging**
