### PR TITLE
Release 13.0.0

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@pitrou , @cyb70289 and others, can you check this version works fine with your code base? I'll do the same with pythran.

**Comment by cyb70289** [comment]
Did a quick test with apache arrow on arm server. No error found.
`-DARROW_COMPUTE=ON -DARROW_PARQUET=ON -DARROW_BUILD_TESTS=ON`

**Comment by serge-sans-paille** [comment]
Everything looks good on pythran bots too: https://github.com/serge-sans-paille/pythran/pull/2188

**Comment by JohanMabille** [comment]
NItpicking: releases should be a commit directly on master / main instead of pull requests. I can cherry-pick the commit and push it directly.

**Comment by JohanMabille** [comment]
The signbit fix has been pushed in #1020  and the release commit has been pushed directly to master, let's close this.

**Pull request closed without merging**
