### PR TITLE
Initial Implementation for the new WASM based instruction set

### PR DESCRIPTION
**Pull request by anutosh491**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Thanks a lot for working on this!
From a methodological point of view (and to ease the work of the reviewer) it would be great if you could focus on a single test file, have it validate, then we can merge the PR and move on to more test. Do you think it's a viable approach?

**Comment by JohanMabille** [comment]
Yes, the initial idea was to first have all the basic arithmetic operations only (more or less everything tested in `https://github.com/xtensor-stack/xsimd/blob/master/test/test_batch.cpp`), and then find a way to reuse the already existing tests in WASM.

**Comment by anutosh491** [comment]
> Thanks a lot for working on this!

Thanks for having a look. Yeah this pr branches out from #943 and I think so Thorsten is trying to port the test files and run them all considering wasm. I guess once that is done we could merge that PR and rebase this one top of that.

**Comment by serge-sans-paille** [comment]
@anutosh491 can you rebase on latest `master` branch? Wasm support for CI has been merged in.

**Comment by anutosh491** [comment]
Sure I'll do it !

**Comment by anutosh491** [comment]
@serge-sans-paille Ahh I think I made a bad commit somewhere and also the commit history looks very messy here. I've pushed my changes on top of current master on a seperate branch (#952). Should make reviewing and merging more easier.

**Pull request closed without merging**
