### PR TITLE
Enables support for FMA when AVX2 is detected on Windows

### LINKED ISSUE #630: xsimd doesn't detect FMA on MSVC
:wave:

I noticed that with MSVC, FMA is never detected because it relies on the `__FMA__` macro, which is GCC and Clang only.

However, from [this StackOverflow question](https://stackoverflow.com/questions/34265982/automatically-generate-fma-instructions-in-msvc) as well as [this MSDN post](blogs.msdn.com/b/vcblog/archive/2014/02/28/avx2-support-in-visual-studio-c-compiler.aspx), MSVC is indeed able to generate FMA instructions with `/arch:AVX2`.

Would it be possible to add support for it, or should it be force enabled from the outside?

(I cannot supply a Godbolt as an example, because it refuses to compile xsimd.)

### PR DESCRIPTION
**Pull request by JohanMabille**
Fixes #630

### CODE REVIEW

**Comment by tomjnixon** [comment]
Should this not enable FMA5? I think with /arch:AVX2 MSVC can generate 256 bit FMA instructions.

**Comment by JohanMabille** [comment]
Ah indeed.

**Comment by serge-sans-paille** [comment]
Can you rebase on master branch now that the clang-format patch is in?

**Comment by JohanMabille** [comment]
sure

**Pull request merged**
