### PR TITLE
Use properly aligned array during xtl testing

### LINKED ISSUE #812: Crash in `include/xsimd/arch/xsimd_avx.hpp:814` when `XSIMD_ENABLE_XTL_COMPLEX` is enabled
With latest xsim 9.0.1 from today, I get a crash in the tests in https://github.com/xtensor-stack/xsimd/blob/31298c883bda0f3dfcf44170f45be242deb78f1a/test/test_batch_complex.cpp#L127
This crashes on all platforms, Windows (latest ClangCl 14.0.5), Linux (Clang 14.0.6) and macOS (latest XCode 13.4).

When `XSIMD_ENABLE_XTL_COMPLEX` is enabled, this leads for me to call stack:
```
xsimd::batch<float, xsimd::fma3<xsimd::avx2> > xsimd::kernel::load_aligned<xsimd::fma3<xsimd::avx2> >(float const*, xsimd::kernel::convert<float>, xsimd::avx const&) (/home/user/Src/xsimd/include/xsimd/arch/xsimd_avx.hpp:814)
xsimd::batch<float, xsimd::fma3<xsimd::avx2> > xsimd::batch<float, xsimd::fma3<xsimd::avx2> >::load_aligned<float>(float const*) (/home/user/Src/xsimd/include/xsimd/types/xsimd_batch.hpp:547)
xsimd::batch<std::complex<float>, xsimd::fma3<xsimd::avx2> > xsimd::kernel::load_complex_aligned<xsimd::fma3<xsimd::avx2>, float, float>(std::complex<float> const*, xsimd::kernel::convert<std::complex<float> >, xsimd::generic const&) (/home/user/Src/xsimd/include/xsimd/arch/generic/xsimd_generic_memory.hpp:353)
xsimd::detail::simd_return_type_impl<std::complex<float>, xtl::xcomplex<float, float, true>, xsimd::fma3<xsimd::avx2> >::type xsimd::load_as<xtl::xcomplex<float, float, true>, xsimd::fma3<xsimd::avx2>, float>(std::complex<float> const*, xsimd::aligned_mode) (/home/user/Src/xsimd/include/xsimd/types/xsimd_api.hpp:1156)
xsimd::detail::simd_return_type_impl<xtl::xcomplex<float, float, true>, xtl::xcomplex<float, float, true>, xsimd::fma3<xsimd::avx2> >::type xsimd::load_as<xtl::xcomplex<float, float, true>, xsimd::fma3<xsimd::avx2>, float, true>(xtl::xcomplex<float, float, true> const*, xsimd::aligned_mode) (/home/user/Src/xsimd/include/xsimd/types/xsimd_api.hpp:1165)
batch_complex_test<xsimd::batch<std::complex<float>, xsimd::fma3<xsimd::avx2> > >::test_load_store_xtl() const (/home/user/Src/xsimd/test/test_batch_complex.cpp:127)
batch_complex_test_load_store_xtl_Test<xsimd::batch<std::complex<float>, xsimd::fma3<xsimd::avx2> > >::TestBody() (/home/user/Src/xsimd/test/test_batch_complex.cpp:661)
...
```

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Should fix #812

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
I wrote 'should fix' because I wasn't able to reproduce. @emmenlau  can you test that patch?

**Comment by emmenlau** [comment]
A first test shows that this fixes the problem on Ubuntu Linux 20.04 with clang 14.0.6. I'll test also in our CI on Windows and macOS next...

**Comment by emmenlau** [comment]
I can confirm the fix works on all platforms! Nice!

**Comment by serge-sans-paille** [comment]
Thanks for checking!

**Pull request merged**
