### PR TITLE
Refactor examples

### PR DESCRIPTION
**Pull request by DerThorsten**
this makes the Mandelbrot example run again.
I refactored the code a bit such that it runs for all supported archs.

Downside of the generic approach is that I rely on `typeid(arch).name()` to print the name of the arch.
One could add a name function to the arch itself.
smth like 
```c++
    struct avx2 : avx
    {
        static constexpr std::string name() {return "avx2";}
        static constexpr bool supported() { return XSIMD_WITH_AVX2; }
        static constexpr bool available() { return true; }
        static constexpr unsigned version() { return generic::version(2, 2, 0); }
    };
```

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
> Downside of the generic approach is that I rely on `typeid(arch).name()` to print the name of the arch.
 #533 adds a `name()` method that returns a `char const*` (can't use an `std::string` which is not constexpr).

**Comment by SylvainCorlay** [comment]
Happy to get this in as soon as the `typeid` call is not required :)

**Comment by DerThorsten** [comment]
`arch::name()` is used instead of `typeid`.
Can be merged.

**Comment by SylvainCorlay** [comment]
Thanks!

**Pull request merged**
