### PR TITLE
Adding pkg-config support

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks!

This looks good to me. You may want to add

```
# Generated pkg-config files
*.pc
```

to the `.gitignore`.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by tdegeus** [comment]
@SylvainCorlay Could the conda version be patched with this PR? (Or rather could there me a patch release?) My Python compiler relies of pkgconfig.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay Could the conda version be patched with this PR? (Or rather could there me a patch release?) My Python compiler relies of pkgconfig.

I think we can make a patch release tomorrow. There were some fixes wrt avx512 issues that were merged as well.

**Pull request merged**
