### PR TITLE
ref #314 First try in order to discuss details and to see how to integrate AVX512 and neon flavor 

### PR DESCRIPTION
**Pull request by ThomasRetornaz**
Add missing saturated sadd ssub
* int8,uint8,int16,uint16,int32,uint32,int64,uint64
* sse/sse3/sse4
* avx/avx2
Test:
* Validated on unbuntu 1804, g++ 7,4
* Pb remains globaly for the entire lib especially in debug with visual 2019
Todo:
* AVX512
* NEON
For the two last how to test ??

### CODE REVIEW

**Comment by ThomasRetornaz** [comment]
Sorry i don't pay attention about complex and fallback. I will try to fix this asap
For fallback where could i put saturated add/sub scalar flavor ?

**Comment by JohanMabille** [comment]
Hi, thanks for this PR!

- you can put the implementation of sadd/ssub for fallback in `xsimd/types/xsimd_fallback.hpp`.
- AVX512 can be tested thanks to the SDE provided by [Intel](https://software.intel.com/en-us/articles/pre-release-license-agreement-for-intel-software-development-emulator-accept-end-user-license-agreement-and-download). You need to have the content of the archive reachable (either by uncompressing in your build directory or by adding the content of the archive to the path with `export PATH=/path/sde-external-8.16.0-2018-01-30-lin/:$PATH`). Then build for the skylake architecture and run the tests with the sde:
    - `cmake . -DDOWNLOAD_GTEST=ON -DTARGET_ARCH=skylake-avx512 -DCMAKE_INSTALL_PREFIX=$YOUR_PREFIX`
    - `make -j6 test_xsimd`
    - `sde64 -skx -- ./test_xsimd`
- Neon needs more configuration, you will have to download additional packages from your distribution depending on which instruction set (armv7 or armv8) and which architecture you want to test. I usually comment out all but the ARM sections in `.travis.yml` and use the CI for testing.

**Comment by JohanMabille** [comment]
> Pb remains globaly for the entire lib especially in debug with visual 2019

Which kind of problems do you have?

**Comment by ThomasRetornaz** [comment]
> 
> 
> > Pb remains globaly for the entire lib especially in debug with visual 2019
> 
> Which kind of problems do you have?

Various :)

* AVX512 not compil at all, i made various fixs (mainly template resolution problems) and end with an internal compiler error .... i will check with an over msvc compiler flavor
* Default sse tests seems flaky, ie no specifics errors is returned but the sub test suite fail
* Debug tests crash when programs cleanup allocated "batch", i set the MSVC secure* to false without sucess Again i will check with an over msvc compiler flavor
Regards
TR

**Comment by ThomasRetornaz** [comment]
> 
> 
> Sorry i don't pay attention about complex and fallback. I will try to fix this asap
> For fallback where could i put saturated add/sub scalar flavor ?

OK i cover AVX512,AVX2,SSE,NEON under linux, remain AVX 
Do you have any subgestion in order to don't make huge copy/paste ? 
Thanks 
Regards
TR

**Comment by JohanMabille** [comment]
Hi,

Regarding the workflow, we prefer rebasing the PRs instead of merging remote branches to avoid history pollution (and to facilitate PR reviews). Could you rebase your branch on the master branch and drop the merge commits? Also it seems that the formatting of some files has changed (indentation of `xsimd_avx512_int16.hpp` for instance), I hope the rebase will fix it.

Regarding the Internal Compiler Error you have, sometimes it happens when the compiler runs out of memory because of too many template instantiations. Splitting the cpp files into smaller ones might fix the issue (you can confirm this hypothesis by simply commenting almost all the tests in the cpp file before you start to split it).

Regarding the refactoring to avoid acopy / paste, you can implement free template functions that contain code common to many implementations in namespace `detail` and call them from the kernels. I am not sure we can factorize more (i.e. between batches of different sizes) since the implementation used different intrinsics.

**Comment by ThomasRetornaz** [comment]
Hello
I fix indent (clangformat misuses) and AVX support. 
All seems good except ssub for AVX uint64_t and unint32_t, i can't figure what i make wrong
Of course the problem is beetween  my desk and my chair but if you have time to take a look
When fixed i will squash commit and rebase
I will take a look on windows side
Thanks
Regards
TR

**Comment by JohanMabille** [comment]
Hi,

Thanks for the fixes. I am a bit swamped with other tasks these days, I may have much time to have a look in the end of the week.

**Comment by ThomasRetornaz** [comment]
> 
> 
> Hi,
> 
> Thanks for the fixes. I am a bit swamped with other tasks these days, I may have much time to have a look in the end of the week.

I rebase and clean commit history  in rev https://github.com/xtensor-stack/xsimd/pull/348/commits/67734a6f702f94d20931e391b68f91a4921bfc64
Sorry i quiet newbie with git ....
If you have time to review, i will made changes asap
ANd of course thanks for the library
Regards 
TR

**Comment by JohanMabille** [comment]
Hi,

No worries! We've all been new to git at some point, and teams behind github repos may have different workflows. I didn't notice in my first comment that you were developing on your master branch, which is usually not recommended. So here is a way to fix that (assuming origin is your fork, and upstream is this repo):

```bash
# Create a new branch ref_314
git checkout -b ref_314
# Resync your local master branch
git checkout master
git fetch upstream
git reset --hard upstream/master
# Resync your remote master branch
git push origin master -f
```

At this point, you have two branches, master (synchronized with both origin and upstream remotes), and ref_314 with your development, which needs to be rebased.

We usually do the following:

```bash
# First, update master (you can skip this since you hard reset it just before)
git checkout master
git pull upstream master
git push origin master
# Optional: create a backup branch in case something goes wrong
git checkout ref_314
git checkout -b ref_314_backup
# Then rebase
git checkout ref_314
git rebase -i master
```

This last command will enter the interactive mode. We usually squash commits like small fixes (like typo, or slight change in the tests) to keep a clean history. However, some fixes might be tricky (because specific to a platform or a compiler bug), in this case it can make sense to keep them.

When everything is fine, you can push your branch and open a new PR (because of the change of branch).

Do not hesitate if you have any question. If you don't feel comfortable with the rebase, let me know when you have fixed your master branch and created the `ref314` branch, I can rebase for you.

**Comment by ThomasRetornaz** [comment]
Hi
Thanks a lots for the moock, i really appreciate :)
Note I pushed to master because in a other project the maintener do this way but yes it much cleaner to make a dedicated branch.
Ok i follow the instructions, may i make something wrong during the rebase steps because i have been surprise by the interactive mode (anyway i have to learn). I will made a new PR
If its not clean i will try again
Thanks again
Regards TR

**Comment by ThomasRetornaz** [comment]
I just finish rebasing. I fail to isolate two commit regarding build system (Visual compil fix). Do i push anyway ?

**Comment by JohanMabille** [comment]
Yes, the advantage is that you won't have any commit taht were already in the master branch, nor "merge" commits, so the diff will be cleaner.

Then we can either squash and merge from Github once the change has been approved, or keep all the commits if you think it is worth doing it.

**Pull request closed without merging**
