### PR TITLE
Run tests on Apple M1

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by JohanMabille** [comment]
Is the title of this PR misleading? Or does Osx13 always imply M1 archtecture in the CI?

**Comment by serge-sans-paille** [comment]
On Tue, Nov 14, 2023 at 01:34:37AM -0800, Johan Mabille wrote:
> Is the title of this PR misleading? Or does Osx13 always imply M1 archtecture
> in the CI?

Osx13 xlarge implies M1, but it's not free :-/

**Comment by JohanMabille** [comment]
Looks like they just released aa free version! See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by JohanMabille** [comment]
OK, that's the issue reported in #956

**Pull request merged**
