### PR TITLE
Enable riscv64 in build system

### PR DESCRIPTION
**Pull request by tekkamanninja**
Signed-off-by: Wei Fu <wefu@redhat.com>

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Thanks for the PR! What are you trying to achieve, this does not add any actual support, it will just allow for the scalar version, right?

**Comment by tekkamanninja** [comment]
> Thanks for the PR! What are you trying to achieve? This does not add any actual support, it will just allow for the scalar version, right?

Hi ,
We are trying to build it on RISC-V (for Fedora 36), but this package failed because of that it miss  a branch for riscv64 :-)
Once we add this patch, we built this on risc64 successfully 

so maybe I should say: "enable riscv64 build"?

would you mind to correct me on this  :-)

**Comment by serge-sans-paille** [comment]
Thanks for the details! Yeah, please amend your commit to reflect that aspect, other wise looks good :-)

**Comment by serge-sans-paille** [comment]
Thanks o/

**Pull request merged**
