### PR TITLE
Fix extract_pair implementation on SSSE3

### LINKED ISSUE #557: [SSE4] extract_pair performance is very bad
When porting my current simd code from intrinsics to xsimd. I see big performance drop from 6.33GB/s to 1.58GB/s. Most drop comes from `extract_pair`. I build with clang-10, -O3, enabled SSE4_2.

Disassembler shows `extract_pair` is using the fallback code [1], not the optimal code based on `_mm_alignr_epi8`[2]. The optimized code is in ssse3, looks it's not inherited by sse4_2 -> sse4_1 -> sse3 -> sse2 -> ....

[1] https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/generic/xsimd_generic_memory.hpp#L14-L35
[2] https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_ssse3.hpp#L23-L45

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Missing default template argument and invalid recursion...

Fix #557

### CODE REVIEW

**Comment by cyb70289** [comment]
I did a quick test, this PR doesn't fix my performance issue.

I wrote a simple test code. The disassembly code looks wrong.
```
#include <memory>
#include <xsimd/xsimd.hpp>

using simd_batch = xsimd::batch<int8_t, xsimd::sse4_2>;

simd_batch test(simd_batch v1, simd_batch v2) {
  return xsimd::extract_pair(v1, v2, 15);
}
```

Build with `g++ -O3 -std=c++11 -c test.cc -msse4.2`

Show disassembled code with `objdump -dC test.o`
```
   0:   f3 0f 1e fa             endbr64
   4:   66 0f 6f c1             movdqa %xmm1,%xmm0
   8:   c3                      retq
```
It simply returns `v2`. I would expect it to be `palignr $0xf,%xmm1,%xmm0`.

**Comment by serge-sans-paille** [comment]
@cyb70289 patch updated, should be good now.

**Comment by cyb70289** [comment]
Thanks @serge-sans-paille , above error is fixed. But the performance issue is still there.

I created a  test code for debugging.
```
#include <xsimd/xsimd.hpp>

using simd_batch = xsimd::batch<int8_t, xsimd::sse4_2>;

const char* FindLast(const char* const data_begin, const char* const data_end) {
  const char* last_crlf = nullptr;

  const simd_batch tag(0x55);

  simd_batch last_tag(0);

  const char* data = data_begin;
  while (data < data_end) {
    simd_batch current = simd_batch::load_unaligned(data);
    data += 16;

    simd_batch tag = static_cast<simd_batch>(current == tag);
    // NOT calling palignr
    simd_batch tag_shift1 = xsimd::extract_pair(tag, last_tag, 15);

    last_tag = tag;

    current &= ~tag_shift1;
    const auto is_crlf = (current == tag);
    if (xsimd::any(is_crlf)) {
      last_crlf = data - 1;
    }
  }

  return last_crlf;
}
```

Tested with both gcc-9.3 and clang-10, -O3, the assembly code does not use `palignr`.
Below assembly is from clang-10. The code around `pextrb` (2c ~ 3c) looks the generated code from extract_pair.
```
0000000000000000 <FindLast(char const*, char const*)>:
   0:   48 39 f7                cmp    %rsi,%rdi
   3:   73 62                   jae    67 <FindLast(char const*, char const*)+0x67>
   5:   66 0f ef d2             pxor   %xmm2,%xmm2
   9:   31 c0                   xor    %eax,%eax
   b:   66 0f 6f 05 00 00 00    movdqa 0x0(%rip),%xmm0        # 13 <FindLast(char const*, char const*)+0x13>
  12:   00
  13:   66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  1a:   00 00 00
  1d:   0f 1f 00                nopl   (%rax)
  20:   f3 0f 6f 1f             movdqu (%rdi),%xmm3
  24:   66 0f 74 cb             pcmpeqb %xmm3,%xmm1
  28:   66 0f db c8             pand   %xmm0,%xmm1
  2c:   66 0f 3a 14 4c 24 e8    pextrb $0xf,%xmm1,-0x18(%rsp)
  33:   0f
  34:   66 0f 3a 14 54 24 f7    pextrb $0xe,%xmm2,-0x9(%rsp)
  3b:   0e
  3c:   66 0f 6f 54 24 e8       movdqa -0x18(%rsp),%xmm2
  42:   66 0f df d3             pandn  %xmm3,%xmm2
  46:   66 0f 74 d1             pcmpeqb %xmm1,%xmm2
  4a:   66 0f d7 ca             pmovmskb %xmm2,%ecx
  4e:   48 8d 57 0f             lea    0xf(%rdi),%rdx
  52:   66 85 c9                test   %cx,%cx
  55:   48 0f 45 c2             cmovne %rdx,%rax
  59:   48 83 c7 10             add    $0x10,%rdi
  5d:   66 0f 6f d1             movdqa %xmm1,%xmm2
  61:   48 39 f7                cmp    %rsi,%rdi
  64:   72 ba                   jb     20 <FindLast(char const*, char const*)+0x20>
  66:   c3                      retq
  67:   31 c0                   xor    %eax,%eax
  69:   c3                      retq
```

**Comment by serge-sans-paille** [comment]
With clang 6 and clang 14
```shell
> clang++ -O3 -S a.cpp -o-  -msse4.2  -Iinclude | grep palignr
palignr	$15, %xmm2, %xmm4
```

with g++ 8.2

```shell
> g++ -O3 -S a.cpp -o-  -msse4.2  -Iinclude | grep palignr 
palignr	$15, %xmm1, %xmm3
```

**Comment by cyb70289** [comment]
Looks I didn't test the latest code. Sorry for the noise.
I've verified this PR does fixes the palignr issue.
Thanks @serge-sans-paille !

**Review by cyb70289 — APPROVED** [review]
LGTM

**Pull request merged**
