### PR TITLE
Implement slides for NEON

### LINKED ISSUE #636: Support shifting whole batches left and right
:wave:

I understand that xsimd's `<<` and `>>` operators shifting batches' elements individually and simultaneously via e.g. `_mm_sll_epi32` for left shifting a `xsimd::batch<uint32_t, xsimd::sse2>`.
However, being able to shift the *whole* batch ie. `_mm_bsrli_si128` would be useful in some cases.

### PR DESCRIPTION
**Pull request by amyspark**
:wave:

This PR completes the implementation of slides for integer batches.

Fixes #636

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Wouldn't that be more efficient through https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=vextq_s8 ?

**Comment by serge-sans-paille** [comment]
(And thanks for doing this, of course o/)

**Comment by amyspark** [comment]
> Wouldn't that be more efficient through https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=vextq_s8 ?

`vextq_s8` extract whole elements with 8-bit granularity; `slide_*` shifts with 1-bit granularity.

**Comment by serge-sans-paille** [comment]
thanks!

**Pull request merged**
