### PR TITLE
add arange to xsimd

### PR DESCRIPTION
**Pull request by wolfv**
This is supposed to be used in the arange `assign_to` as well as a potential `simd_step`.

### CODE REVIEW

**Comment by wolfv** [comment]
I'm very open to suggestions regarding the interface.

**Comment by abique** [comment]
There is absolutely no comments in the header.
What is this function supposed to do... ?

There is no unit test as well.

**Comment by wolfv** [comment]
This is a fast implementation of filling a vector with a sequence of numbers. Like numpy Stange

**Comment by serge-sans-paille** [comment]
xsimd no longer has generic algorithms working on sequences, closing.

**Pull request closed without merging**
