### PR TITLE
Add changelog, tracing changes back to 8.0.1

### LINKED ISSUE #879: No changelogs
Sorry if this is a stupid question, but what is the best way to tell what the changes are for a new major version? I can't seem to find any kind of changelog or updated documentation. How can I find out what the major changes are between e.g. version 10.0.0 and 9.0.1 apart from reading through all commits?

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Fix #879

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @JohanMabille

**Comment by JohanMabille** [comment]
Thanks for tackling this. Just a question, regarding your name + email after each version, does that mean that you authored all the commits in the version or that you tagged the release?

**Comment by serge-sans-paille** [comment]
On Tue, Jan 31, 2023 at 02:27:01AM -0800, Johan Mabille wrote:
> Thanks for tackling this. Just a question, regarding your name + email after
> each version, does that mean that you authored all the commits in the version
> or that you tagged the release?

That I wrote the Changelog. But I'm not strongly attached to that. It probably
makes more sense to have the contact of the guy who made the release?

**Comment by JohanMabille** [comment]
> I don't know, usually (i.e. in the other repos of this stack) we don't put anything since the contributors' list is available on github (sorry I should have mentioned that in the previous post, I didn't think you would update the PR so fast ;))

**Comment by serge-sans-paille** [comment]
ok. I'll update it once again ;-)

**Comment by JohanMabille** [comment]
Let me do it tonight, I'll make a pass on the opened PRs.

**Comment by serge-sans-paille** [comment]
LGTM, please squash the commit before merging ;-)

**Pull request merged**
